name: Deploy Express and Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated version

    - name: Set up Node.js
      uses: actions/setup-node@v3 # Updated version
      with:
        node-version: '18.x' # Use a specific Node.js version if needed

    - name: Set up SSH agent
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Use ssh-keyscan to add the server to known_hosts
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          set -e # Exit if any command fails

          # Go to the backend project directory and pull the latest code
          cd /home/kenya123/codeLabs/clients/ # Adjust to your project root
          git pull origin master
          npm install --production
          
          # Restart the backend using systemd
          sudo systemctl restart myclients.service
          sudo systemctl status myclients.service # Optional: Check status for debugging

          # Optionally update frontend files and reload Nginx
          # cd /path/to/your/frontend/files
          # git pull origin main
          # sudo cp -R * /var/www/your-nginx-site-root
          # sudo systemctl reload nginx
        EOF
